environment: production
port: 5000
db:
  host: localhost
  port: 5432
  user: myuser
  password: mypassword
  db_name: mydatabase
  ssl_mode: disable
  max_open_conns: 10
  max_idle_conns: 10
  conn_max_lifetime: 5
jwt_secret: "your_secret_key"